name: PR_unit_tests

on:
  pull_request:
    branches:
      - 'main'

jobs:
  Unit-test:
    name: Run unit tests on PR in main
    runs-on: ubuntu-20.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2  # Versi칩n correcta de la acci칩n
        with:
          java-version: '17'         # Configuramos Java 17
          distribution: 'temurin'    # Usamos la distribuci칩n Temurin

      - name: Verify Java version
        run: java -version           # Verifica que se est치 usando Java 17

      - name: Run unit tests
        run: ./gradlew test

      - name: Upload HTML test report
        uses: actions/upload-artifact@v3
        with:
          name: index.html
          path: app/build/reports/tests/testDebugUnitTest/index.html

      - name: Upload test report directory
        uses: actions/upload-artifact@v3
        with:
          name: testDebugStuff
          path: app/build/reports/tests/testDebugUnitTest/