name: Measure coverage

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Coverage
        run: ./gradlew allDebugCoverage

      - name: Jacoco Report to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.1
        with:
          report-paths: ${{ github.workspace }}/__tests__/__fixtures__/input/report.xml
          github-token: ${{ secrets.GH_TOKEN }}
          pull-request-title: 'JaCoCo Report 🤖'
          delete-previous-comment: true
          min-overall-instructions-coverage: 50
          min-overall-branch-coverage: 50
          min-modified-files-instructions-coverage: 70
          min-modified-files-branch-coverage: 70
      - name: Get the Coverage Info
        run: |
          echo "Overall instructions coverage ${{ steps.jacoco.outputs.overall-instructions-coverage }}"
          echo "Overall branch coverage ${{ steps.jacoco.outputs.overall-branch-coverage }}"
          echo "Overall instructions coverage ${{ steps.jacoco.outputs.modified-files-instructions-coverage }}"
          echo "Overall branch coverage ${{ steps.jacoco.outputs.modified-files-branch-coverage }}"