name: Measure coverage

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Module Coverage
        run: ./gradlew debugCoverage

      - name: Jacoco Report to PR
        id: jacoco
        uses: madrapps/jacoco-report@more-events
        with:
          paths: |
            ${{ github.workspace }}/**/build/reports/jacoco/**/**.xml,
            ${{ github.workspace }}/**/build/reports/jacoco/**/**.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 45
          min-coverage-changed-files: 84
          title: '# :lobster: `Coverage Report`'
          update-comment: true
          comment-type: 'both'
          pass-emoji: ':green_circle:'
          fail-emoji: ':red_circle:'
          continue-on-error: true
          debug-mode: true

      - name: Get the Coverage info
        run: |
          echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
          echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"