name: Measure coverage

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Coverage
        run: ./gradlew allDebugCoverage

      - name: Add coverage to PR
        id: jacoco
        uses: juliusiglesia/jacoco-report-publisher@0.0.2
        with:
          report-paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          github-token: ${{ secrets.GITHUB_TOKEN }}
          min-overall-instructions-coverage: 50
          min-overall-branch-coverage: 50
          min-modified-files-instructions-coverage: 70
          min-modified-files-branch-coverage: 70